name = "claude-cursor-sync"
main = "src/index.ts"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "CLAUDE_CURSOR_SYNC", class_name = "ClaudeCursorSyncDO" },
  { name = "MCP_OBJECT", class_name = "MyMCP" }
]

[[migrations]]
tag = "v1"
new_classes = ["ClaudeCursorSyncDO", "MyMCP"]

# Add environment variables if needed
[vars]
DEBUG = "true"

# Dev configuration
[dev]
port = 8787

[observability]
enabled = true