name = "claude-cursor-sync"
main = "src/index.ts"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "5c3e9cf4d55ce171b844fad0931607f9" # Half Dozen account

# Phase 2: Adding both bindings now that migrations have been applied
[durable_objects]
bindings = [
  { name = "MCP_OBJECT", class_name = "MyMCP" },
  { name = "CLAUDE_CURSOR_SYNC", class_name = "ClaudeCursorSyncDO" }
]

# Migrations have been successfully applied in Phase 1
[[migrations]]
tag = "v1" 
new_classes = ["MyMCP"]

[[migrations]]
tag = "v2"
new_classes = ["ClaudeCursorSyncDO"]

# Add environment variables if needed
[vars]
DEBUG = "true"
PHASE = "2"

# Dev configuration
[dev]
port = 8787

[observability]
enabled = true